---
- name: restart logstash
  throttle: 1
  systemd:
    name: logstash
    enabled: yes
    state: restarted
    daemon_reload: yes

# 检查运行状态
- name: logstash status check
  include_tasks: check.yml