---
- name: restart elasticsearch
  throttle: 1
  systemd:
    name: elasticsearch
    enabled: yes
    state: restarted
    daemon_reload: yes

# 检查运行状态
- name: elasticsearch status check
  include_tasks: check.yml