---
- name: restart haproxy
  throttle: 1
  systemd:
    name: haproxy
    enabled: yes
    state: restarted
    daemon_reload: yes

# 检查运行状态
- name: haproxy status check
  include_tasks: check_haproxy.yml


- name: restart keepalived
  throttle: 1
  systemd:
    name: keepalived
    enabled: yes
    state: restarted
    daemon_reload: yes

# 检查运行状态
- name: keepalived status check
  include_tasks: check_keepalived.yml